name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.manifest/**'
      - '.original_manifest/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ajs3ra8/loan-app-java:${{ github.run_number }}

      - name: Checkout source code
        uses: actions/checkout@v4   

      - name: login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

     
      - name: Create manifest
        run: |
          mkdir -p manifests
          cp original_manifest/* manifests/
          sed -i "s/IMAGE_TAG/${{ github.run_number }}/g" ./manifests/deployment.yaml

          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          git add manifests/deployment.yaml
          git commit -m "Add Kubernetes manifests"
          git push

